### ISSUE TITLE
View startup profile

### ISSUE THREAD

**Issue by LAashley** [outboxafrica/youthinnovationplatform#18]
What information should be provided in the startup profile page for different innovations in their respective stages?

**Comment by richardzulu** [comment]
This should be changed to reflect the level of detail required depending on the stage of the innovator as per the SRS.

**Comment by richardzulu** [comment]
Team members can be added when a user [innovator] is adding their solution to the platform. Clicking "Add team member" should open up the "Edit your profile" form for the user to fill.
